DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cname VARCHAR(64) NOT NULL,
  cdescr VARCHAR(255) NOT NULL,
  createdat TIMESTAMP AS CURRENT_TIMESTAMP,
  modifiedat TIMESTAMP AS CURRENT_TIMESTAMP
);